imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

## ########################################################################
## Parameters
## ########################################################################
parameters:
    locale: en

## ########################################################################
## Framework
## ########################################################################
framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: "%kernel.project_dir%/web/build/manifest.json"
    php_errors:
        log: true

## ########################################################################
## Twig
## ########################################################################
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      ws_uri: wss://upnext.fm:8080

## ########################################################################
## Doctrine
## ########################################################################
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

## ########################################################################
## Doctrine Migrations
## ########################################################################
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

## ########################################################################
## Swiftmailer
## ########################################################################
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

## ########################################################################
## FOSUser
## ########################################################################
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

## ########################################################################
## JWTAuthenticationBundle
## ########################################################################
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

## ########################################################################
## GesdinetJWTRefreshTokenBundle
## ########################################################################
gesdinet_jwt_refresh_token:
    ttl: 604800
    firewall: api_refresh_token

## ########################################################################
## CORS
## ########################################################################
nelmio_cors:
    defaults:
        allow_origin:   ["%cors_allow_origin%"]
        allow_methods:  ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers:  ["content-type", "authorization"]
        expose_headers: ["link"]
        max_age:        3600
    paths:
        '^/': ~

## ########################################################################
## Redis
## ########################################################################
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%snc_redis_clients_default_dsn%"
        session:
            type: predis
            alias: session
            dsn: "%snc_redis_clients_session_dsn%"
    session:
        client: session

## ########################################################################
## Websockets
## ########################################################################
gos_web_socket:
    server:
        port: "%gos_web_socket_server_port%"
        host: "%gos_web_socket_server_host%"
        router:
            resources:
                - "%kernel.root_dir%/config/pubsub.yml"
