imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: "@AdminBundle/Resources/config/services.yml" }

## ########################################################################
## Parameters
## ########################################################################
parameters:
  locale: en

## ########################################################################
## Framework
## ########################################################################
framework:
  #esi: ~
  translator: { fallbacks: ['%locale%'] }
  secret: '%secret%'
  router:
    resource: '%kernel.project_dir%/app/config/routing.yml'
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  serializer: { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale: '%locale%'
  trusted_hosts: ~
  session:
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    handler_id: app.session.handler
  fragments: ~
  http_method_override: true
  assets:
    json_manifest_path: "%kernel.project_dir%/web/build/manifest.json"
  php_errors:
    log: true

## ########################################################################
## Twig
## ########################################################################
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  globals:
    ws_uri: wss://upnext.fm:8080
    founding_users: "%app_founding_users%"
    materialize: true
    activeTab: "home"

## ########################################################################
## Doctrine
## ########################################################################
doctrine:
  dbal:
    driver: pdo_mysql
    host: '%database_host%'
    port: '%database_port%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

## ########################################################################
## Doctrine Migrations
## ########################################################################
doctrine_migrations:
  dir_name: "%kernel.root_dir%/DoctrineMigrations"
  namespace: Application\Migrations
  table_name: migration_versions
  name: Application Migrations

## ########################################################################
## Swiftmailer
## ########################################################################
swiftmailer:
  transport:  "%mailer_transport%"
  host:       "%mailer_host%"
  username:   "%mailer_user%"
  password:   "%mailer_password%"
  port:       "%mailer_port%"
  encryption: "%mailer_encryption%"
  auth_mode:  "%mailer_auth_mode%"
  spool:      { type: memory }

## ########################################################################
## FOSUser
## ########################################################################
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"
  registration:
    form:
      type: AppBundle\Form\RegistrationType

## ########################################################################
## JWTAuthenticationBundle
## ########################################################################
lexik_jwt_authentication:
  private_key_path: '%jwt_private_key_path%'
  public_key_path:  '%jwt_public_key_path%'
  pass_phrase:      '%jwt_key_pass_phrase%'
  token_ttl:        '%jwt_token_ttl%'
  token_extractors:
    authorization_header:
      enabled: true
      prefix:  Bearer
      name:    Authorization
    cookie:
      enabled: true
      name:    token
    query_parameter:
      enabled: false
      name:    token

## ########################################################################
## GesdinetJWTRefreshTokenBundle
## ########################################################################
gesdinet_jwt_refresh_token:
  ttl: 604800
  firewall: api_refresh_token

## ########################################################################
## CORS
## ########################################################################
nelmio_cors:
  defaults:
    allow_origin:   ["%cors_allow_origin%"]
    allow_methods:  ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
    allow_headers:  ["content-type", "authorization"]
    expose_headers: ["link"]
    max_age:    3600
  paths:
    '^/': ~

## ########################################################################
## Redis
## ########################################################################
snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: "%snc_redis_clients_default_dsn%"
    session:
      type: predis
      alias: session
      dsn: "%snc_redis_clients_session_dsn%"
    websocket_storage:
      type: predis
      alias: websocket_storage
      dsn: "%snc_redis_clients_websocket_storage%"
    video:
      type: predis
      alias: video
      dsn: "%snc_redis_clients_video_dsn%"
    rooms:
      type: predis
      alias: rooms
      dsn: "%snc_redis_clients_rooms_dsn%"
  session:
    client: session
    locking: false

## ########################################################################
## Elasticsearch
## ########################################################################
fos_elastica:
    clients:
      default:
        host: localhost
        port: 9200
    serializer: ~
    indexes:
      app:
        types:
          video:
            serializer:
              groups: [elastica]
            persistence:
              driver: orm
              model: AppBundle\Entity\Video
              provider: ~
              finder: ~
          video_log:
            serializer:
              groups: [elastica]
            persistence:
              driver: orm
              model: AppBundle\Entity\VideoLog
              provider: ~
              finder: ~
          chat_log:
            serializer:
              groups: [elastica]
            persistence:
              driver: orm
              model: AppBundle\Entity\ChatLog
              provider: ~
              finder: ~

## ########################################################################
## Websockets
## ########################################################################
gos_web_socket:
  server:
    port: "%gos_web_socket_server_port%"
    host: "%gos_web_socket_server_host%"
    router:
      resources:
        - "%kernel.root_dir%/config/pubsub.yml"
  client:
    firewall: main
    session_handler: "@app.session.handler"
    storage:
      driver: "@app.storage.websocket_driver"

## ########################################################################
## RabbitMQ
## ########################################################################
old_sound_rabbit_mq:
  connections:
    default:
      host:     "%rabbit_mq_connections_default_host%"
      port:     "%rabbit_mq_connections_default_port%"
      user:     "%rabbit_mq_connections_default_user%"
      password: "%rabbit_mq_connections_default_pass%"
      vhost:    "/"
      lazy:     true
  producers:
    save_video:
      connection: default
      exchange_options:
        name: "save-video"
        type: direct
      service_alias: my_app_service # no alias by default
  consumers:
    save_video:
      connection: default
      exchange_options:
        name: "save-video"
        type: direct
      queue_options:
        name: "save-video"
      callback: app_rabbitmq_save_video_consumer
